### ISSUE TITLE
Arrow Glitch! (Please Fix <3)

### ISSUE THREAD

**Issue by ghost** [killhellokitty/Candra-Themes-3.20#3]
Here is a picture of the issue on XFCE, it's the white bit at the bottom right. It actually turns a normal grey Candra colour when you mouse over it, but when you don't... It looks glitched.

![screenshot_2016-10-14_02-58-21](https://cloud.githubusercontent.com/assets/7698035/19373224/4fc3b51c-91ba-11e6-80bf-843f5e1345f9.png)

**Comment by killhellokitty** [comment]
This theme is old Gtk3.20.  I intend on updating it in the near future (time willing).

**Comment by ghost** [comment]
Great man, it's good to see you back!
