### ISSUE TITLE
Wallpaper is overlayed (Nemo, Cinnamon).

### ISSUE THREAD

**Issue by vlad0337187** [killhellokitty/Candra-Themes-3.20#4]
When Desktop - is active application - than there is no visible wallpaper at all - it changes to theme's color.
When it's not active application - wallpaper becomes semi-visible from that overlay:
![2016-10-26 16-51-53](https://cloud.githubusercontent.com/assets/12682937/19728628/d4c027e6-9b9c-11e6-9aec-31f74bb91050.png)
![2016-10-26 16-51-51](https://cloud.githubusercontent.com/assets/12682937/19728629/d4c2aed0-9b9c-11e6-9918-820e60ef094c.png)

This problem appears in all variations of this theme.
Theme version: Candra-Themes-3.20-2 05102016

System: Debian unstable x64 Cinnamon

**Comment by killhellokitty** [comment]
This theme is old Gtk3.20.  I intend on updating it in the near future (time willing).
