### ISSUE TITLE
firefox upgrade .50 changes the color of bookmarks folders in darker theme

### ISSUE THREAD

**Issue by ghost** [killhellokitty/Candra-Themes-3.20#5]
Yesterday I upgraded firefox to 50.0-1, and detected two small issues in the default theme for the browser. When you select a bookmark folder the colors changes to something like grey, and the fonts become ilegibles. I supose is too soon to know if the problem is only of firefox, or if has broke a little part of configuration theme. I use the darker theme. The dark one has not problem and work fine as always. The second issue is about the downloads folder. The "box" (sorry I don't know the exactly how it names) has become transparent and ilegible too. I use the darker theme on arch linux 64.
![wed_nov_16_00 43 58_2016](https://cloud.githubusercontent.com/assets/23488423/20329120/b32dc62e-ab96-11e6-84b5-636e76c65393.jpg)
(Don't know if have been a good idea, but I have put the same on devianart too. Sorry if not..)

**Comment by ghost** [comment]
For the meantime I suggest using the "FT Deepdark Theme", it will fix your issue and it fits in nicely with the theme. I haven't seen killhellokitty reply in a long time, hopefully he/she's just taking a hiatus :(

**Comment by killhellokitty** [comment]
This theme is old Gtk3.20.  I intend on updating it in the near future (time willing).

**Comment by saltasatelites** [comment]
Hi, killhellokitty. I was sure to come back in summer!
